services:
  # --- ALTYAPI SERVİSLERİ ---
  shopdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shop-db
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1434:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  shopredis:
    image: redis:alpine
    container_name: shop-redis
    ports:
      - "6379:6379"
    volumes:
      - redisvolume:/data

  seq:
    image: datalust/seq:latest
    container_name: ecommerce-seq
    restart: unless-stopped
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  shoprabbitmq:
    image: masstransit/rabbitmq
    container_name: shop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqvolume:/var/lib/rabbitmq

  # --- MİKROSERVİSLER ---
  identity-service:
    container_name: identity-service
    build:
      context: .
      dockerfile: src/Services/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Server=shopdb;Database=IdentityDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - Serilog__SeqUrl=http://seq
    depends_on:
      - shopdb
      - seq

  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: src/Services/ProductService/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Server=shopdb;Database=ProductDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - RabbitMQ__Host=shoprabbitmq
      - Serilog__SeqUrl=http://seq
    depends_on:
      - shopdb
      - shoprabbitmq
      - seq

  basket-service:
    container_name: basket-service
    build:
      context: .
      dockerfile: src/Services/BasketService/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - RedisSettings__ConnectionString=shopredis:6379
      - RabbitMQ__Host=shoprabbitmq
      - Serilog__SeqUrl=http://seq
    depends_on:
      - shopredis
      - shoprabbitmq
      - seq

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: src/Services/OrderService/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__DefaultConnection=Server=shopdb;Database=OrderDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      - RabbitMQ__Host=shoprabbitmq
      - Serilog__SeqUrl=http://seq
    depends_on:
      - shopdb
      - shoprabbitmq
      - seq

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: src/Gateways/ApiGateway/Dockerfile 
    ports:
      - "5153:80"
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - ReverseProxy__Clusters__auth-cluster__Destinations__destination1__Address=http://identity-service:80
      - ReverseProxy__Clusters__product-cluster__Destinations__destination1__Address=http://product-service:80
      - ReverseProxy__Clusters__basket-cluster__Destinations__destination1__Address=http://basket-service:80
      - ReverseProxy__Clusters__order-cluster__Destinations__destination1__Address=http://order-service:80
      - Serilog__SeqUrl=http://seq
    depends_on:
      - identity-service
      - product-service
      - basket-service
      - order-service

volumes:
  sqlvolume:
  redisvolume:
  rabbitmqvolume: