version: '3.4'

services:
  # 1. SQL Server (Product Service için)
  shopdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shop-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  # 2. Redis (Basket Service için) - İŞTE BU EKSİKTİ!
  shopredis:
    image: redis:alpine
    container_name: shop-redis
    ports:
      - "6379:6379"
    volumes:
      - redisvolume:/data

  # 3. RabbitMQ (Haberleşme için - Yarın lazım olacak)
  shoprabbitmq:
    image: masstransit/rabbitmq
    container_name: shop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqvolume:/var/lib/rabbitmq

volumes:
  sqlvolume:
  redisvolume:
  rabbitmqvolume: